version: 2
jobs:
  test:
    filters:
      branches:
        only:
          - master
    docker:
      - image: circleci/node:12
        environment:
          PGHOST: 127.0.0.1
          PGPORT: 5432
          PGUSER: nest
          PGPASSWORD: 123
          PGDATABASE: nest-app

      - image: circleci/postgres
        environment:
          POSTGRES_USER: nest
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: nest-app
    steps:
      - checkout

      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn

      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Run test
          command: npm run test:cov

      - store_artifacts:
          path: ./coverage
          destination: coverage


workflows:
  version: 2
  build_and_test:
    jobs:
      - test
